import type { TileVariantIndex } from '../types/tileset'

export type TerrainKey = "grass" | "dirt" | "water" | "stone"

export const BUILTIN_TERRAIN_ASSETS: Record<TerrainKey, Record<TileVariantIndex, string>> = {
  grass: {
    1: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mOw3phGU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAMBrSEycHIXCAAAAAElFTkSuQmCC',
    2: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mOw3Z5JU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAIwQdEyzs3DpAAAAAElFTkSuQmCC',
    3: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mOw25NDU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULANDWmEx9ZGS0AAAAAElFTkSuQmCC',
    4: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mNwOFRAU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULANnjyExfX7NiAAAAAElFTkSuQmCC',
    5: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mNwOl5MU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAGQg8Ey6liD6AAAAAElFTkSuQmCC',
    6: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mNwOVtGU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAC/FHFsKyYsoAAAAAElFTkSuQmCC',
    7: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mNwu1RJU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULALnzRFtpQljiAAAAAElFTkSuQmCC',
    8: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mPwuFFDU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAIWYcFtIqOm+AAAAAElFTkSuQmCC',
    9: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mPwutdAU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAI6loFuFYMyyAAAAAElFTkSuQmCC',
  },
  dirt: {
    1: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mOY4MROU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAKSfZC6kUNeuAAAAAElFTkSuQmCC',
    2: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mOY4sJOU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAD0tfC5Ue0jiAAAAAElFTkSuQmCC',
    3: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mOY6cZOU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULABsjmC51dA+sAAAAAElFTkSuQmCC',
    4: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mOY68FOU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULALOisC60U3UBAAAAAElFTkSuQmCC',
    5: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mNY5MVBU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAM8A0C5B34lnAAAAAElFTkSuQmCC',
    6: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mNY5sNBU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAGeO6C5BlrG5AAAAAElFTkSuQmCC',
    7: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mNY7cdBU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAEWEBD2klQKqAAAAAElFTkSuQmCC',
    8: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mNYH8BBU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAN4DHD1P2TknAAAAAElFTkSuQmCC',
    9: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mPYEsxJU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULADrYQD1k3ungAAAAAElFTkSuQmCC',
  },
  water: {
    1: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsAtkXxuZyxQ+hMH+S/WcikAgEAgEAoFAIPgSLBKGJFuFcuGsAAAAAElFTkSuQmCC',
    2: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsEtkYSsZyhQ+hMH+S/WcikAgEAgEAoFAIPgSLBOTVFs8WqafAAAAAElFTkSuQmCC',
    3: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsGtkZTOZyBQ+hMH+S/WcikAgEAgEAoFAIPgSLBCghFtElMsrAAAAAElFTkSuQmCC',
    4: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsKtkaEPZxhQ+hMH+S/WcikAgEAgEAoFAIPgSLJB9vFs4VT6xAAAAAElFTkSuQmCC',
    5: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsMtkbEtZxRQ+hMH+S/WcikAgEAgEAoFAIPgSLI2K7FuuIpr7AAAAAElFTkSuQmCC',
    6: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsOtkb1vZwxQ+hMH+S/WcikAgEAgEAoFAIPgSLEkvGGqxg3OlAAAAAElFTkSuQmCC',
    7: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsCtlcmNZwhQ+hMH+S/WcikAgEAgEAoFAIPgSLIukTGo2IQxhAAAAAElFTkSuQmCC',
    8: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsEtldmvZwBQ+hMH+S/WcikAgEAgEAoFAIPgSLIixfGo4FkF5AAAAAElFTkSuQmCC',
    9: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NMQ0AAAgDsMnCPL44UcFB0qR/Uz2nIhAIBAKBQCAQCL4ECwidtGrwKpg6AAAAAElFTkSuQmCC',
  },
  stone: {
    1: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mMoa5pMU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAIl0LFumbnb6AAAAAElFTkSuQmCC',
    2: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mOoaptOU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAJqBXFvC3n0hAAAAAElFTkSuQmCC',
    3: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mOo7ZpDU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAKOOjFsjcReYAAAAAElFTkSuQmCC',
    4: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42mNo7FtIU8QwasGoBaMWjFowasGoBaMWjFowasGoBaMWDBULAPIDwFuAR4jeAAAAAElFTkSuQmCC',
    5: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsCtvATvY0xQ+hMH+S/WcikAgEAgEAoFAIPgSLAMf8FvLNbaTAAAAAElFTkSuQmCC',
    6: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsItvAkOY0hQ+hMH+S/WcikAgEAgEAoFAIPgSLAwsIGrRp+76AAAAAElFTkSuQmCC',
    7: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAKklEQVR42u3NQQkAAAgEsOuPCQxhRlP4EAb7L9VzKgKBQCAQCAQCgeBLsB05UGquxAI/AAAAAElFTkSuQmCC',
    8: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAK0lEQVR42mOYMG8zTRHDqAWjFoxaMGrBqAWjFoxaMGrBqAWjFoxaMFQsAABrroRqrETP/gAAAABJRU5ErkJggg==',
    9: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAK0lEQVR42mOYsngHTRHDqAWjFoxaMGrBqAWjFoxaMGrBqAWjFoxaMFQsAAD7i7xqiDbCMAAAAABJRU5ErkJggg==',
  },
}
